name:                dafny-pretty-progress
version:             1.0.0.0
author:              Wolf Honoré
maintainer:          wolfhonore@gmail.com
copyright:           "MIT"

dependencies:
  - base ^>= 4.18.0
  - text ^>= 2.0.0
  - containers ^>= 0.6.0
  - mtl ^>= 2.3.0
  - regex-tdfa ^>= 1.3.2
  - ansi-terminal ^>= 1.0.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: lib

executables:
  dafny-pretty-progress-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dafny-pretty-progress
